# SHIEKH MUHAMMAD AHSAN TARIQ

# ST ID: PIAIC93475

# AIC BATCH-07



In [2]:
import numpy as np

In [3]:
#01 version check
print(np.__version__)

1.18.1


In [6]:
#02 creating array
a=np.array([2,3,4,5])
print(a)

[2 3 4 5]


In [7]:
#03 creaing 2D array
b=np.array([(1,2,3),(4,5,6)])
print(b)

[[1 2 3]
 [4 5 6]]


In [21]:
#04 finding dimension
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a.ndim)

2


In [9]:
#05 item size
a = np.array([1,2,3])
print(a.itemsize)

4


In [10]:
#06 DType
a = np.array ([11,23,44])
print(a.dtype)

int32


In [14]:
#07 rearrange
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [18]:
#08 reshape
arr=np.array([2,4,6,8,10,12,14,16,18,20])
x=arr.reshape(5,2)
print(x)

[[ 2  4]
 [ 6  8]
 [10 12]
 [14 16]
 [18 20]]


In [19]:
#09 size
a=np.array([1,2,3,4])
print(a.size)

4


In [120]:
#10 type
a=np.array([1,2,3,4])
type(a)

numpy.ndarray

In [20]:
#11 slicing of array
a = np.array([1,2,3,4,5,6,7,8,9,10])
print(a[2:7])

[3 4 5 6 7]


In [60]:
#12 print elements at diff indexes
array1d = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(array1d[1])
print(array1d[-1])
print(array1d[3])   
print(array1d[-4])

2
8
4
5


In [61]:
#13 printing all elements
array1d = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(array1d[[0, -1]])

[1 8]


In [64]:
#14 indexing in multidimensional array
arr = np.array([[[1, 2, 3], [4, 5, 6]], 
                [[7, 8, 9], [10, 11, 12]]])
print(arr[0, 0, 1])
print(arr[0, 1, 1])
print(arr[0, 1, 0])

2
5
4


In [22]:
#15 max number in array
a = np.array([1,2,3,4,5,6,7,8,9,10])
print(a.max())

10


In [23]:
#16 min number in array
a = np.array([1,2,3,4,5,6,7,8,9,10])
print(a.min())

1


In [24]:
#17 Addition operation
a = np.array([1,3,5,7])
b = np.array([2,4,6,8])
print(a+b)


[ 3  7 11 15]


In [25]:
#18 Subtraction operation
a = np.array([1,3,5,7])
b = np.array([2,4,6,8])
print(b-a)

[1 1 1 1]


In [26]:
#19 Multiplication operation
a = np.array([1,3,5,7])
b = np.array([2,4,6,8])
print(a*b)

[ 2 12 30 56]


In [28]:
#20 Division operation
a = np.array([4,8,18,48])
b = np.array([2,4,6,8])
print(a/b)

[2. 2. 3. 6.]


In [34]:
#21 Vertical Stacking
a = np.array([(1,3,5,7),(4,5,6,7)])
b = np.array([(1,2,3,4),(5,6,7,8)])
c=np.vstack((a,b))
print(c)

[[1 3 5 7]
 [4 5 6 7]
 [1 2 3 4]
 [5 6 7 8]]


In [36]:
#22 Horizontal stacking
a = np.array([(1,2,3),(4,5,6)])
b = np.array([(1,2,3),(4,5,6)])
print(np.hstack((a,b)))

[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


In [68]:
#23 Appending array vertically after each other
a1 = np.array([[1, 2, 3], [4, 5, 6]])
b1 = np.array([[7, 8, 9], [10, 11, 12]])
print(np.append(a1, b1, axis=0)) 

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [69]:
#24 Appending array horizontally after each other
a1 = np.array([[1, 2, 3], [4, 5, 6]])
b1 = np.array([[7, 8, 9], [10, 11, 12]])
print(np.append(a1, b1, axis=1)) 

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [39]:
#25 ntersection
a = np.array([1,2,3,2,3,4,3,5,6])
b = np.array([2,1,2,7,4,9,4,9])
np.intersect1d(a,b)

array([1, 2, 4])

In [40]:
#26 Union
a = np.array([1,2,3,4])
b = np.array([5,6,7,8,9])
np.union1d(a,b)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
#27 Difference
array1 = np.array([0, 10, 20, 90, 40])
array2 = np.array([10,30, 40, 50, 70])
np.setdiff1d(array1, array2)

array([ 0, 20, 90])

In [48]:
#28 position where elements matched
a = np.array([1,2,5,4,6])
b = np.array([1,4,5,6,6])
x=np.where(a==b)
print(x)

(array([0, 2, 4], dtype=int64),)


In [49]:
#29 Converting 2D into 1D
x= np.array([[1,2,3],[3,4,5]])
print(x.ravel())

[1 2 3 3 4 5]


In [53]:
#30 Repeating elements
x = np.array([[1,2],[3,4]])
print(np.repeat(x, 2))

[1 1 2 2 3 3 4 4]


In [55]:
#31 Comparing arrays
a = np.array([1, 2])
b = np.array([3, 6])
print("for operation a > b")
print(np.greater(a, b))
print("for operation a >= b")
print(np.greater_equal(a, b))
print("for operation a < b")
print(np.less(a, b))
print("for operation a <= b")
print(np.less_equal(a, b))

for operation a > b
[False False]
for operation a >= b
[False False]
for operation a < b
[ True  True]
for operation a <= b
[ True  True]


In [56]:
#32 Uniformly distributed integers in a given range.
print(np.random.randint(10, size=6))
print(np.random.randint(10, size=(2,3)))

[7 3 1 0 2 4]
[[3 3 8]
 [5 0 8]]


In [57]:
#33 Diagonal matrix
print(np.diag(np.arange(2, 10, 2)))

[[2 0 0 0]
 [0 4 0 0]
 [0 0 6 0]
 [0 0 0 8]]


In [58]:
#34 identity matrix
print(np.identity(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [88]:
#35 numpy mathametical function (SIN)
a = np.array([[0, 30, 45, 60, 90]])
x = np.deg2rad(a)

print("The sin of array after converting in radians:\n ")
print(np.sin(x))

The sin of array after converting in radians:
 
[[0.         0.5        0.70710678 0.8660254  1.        ]]


In [86]:
#36 numpy mathametical function (COS)
a=[0,30,45,60,90]
print(np.cos(a))

[ 1.          0.15425145  0.52532199 -0.95241298 -0.44807362]


In [87]:
#37 numpy mathametical function (TAN)
a=[0,30,45,60,90]
print(np.tan(a))

[ 0.         -6.4053312   1.61977519  0.32004039 -1.99520041]


In [89]:
#38 calculating exponent
a=[0,30,45,60,90]
print(np.exp(a))

[1.00000000e+00 1.06864746e+13 3.49342711e+19 1.14200739e+26
 1.22040329e+39]


In [90]:
#39 calculating log
a=[10,20,30,40,50]
print(np.log10(a))

[1.         1.30103    1.47712125 1.60205999 1.69897   ]


In [91]:
#40 finding square
a=[10,20,30,40,50]
print(np.power(a, 2))

[ 100  400  900 1600 2500]


In [108]:
#41 finding squareroot
a = np.array([4,9,16,25])
print(np.sqrt(a))

[2. 3. 4. 5.]


In [93]:
#42 finding remainder after division
np.remainder([8, 17], [2, 3])

array([0, 2], dtype=int32)

In [101]:
#43 making elements reciprocal
a=[2,4,5,0.1]
print(np.reciprocal(a))

[ 0.5   0.25  0.2  10.  ]


In [102]:
#44 finding mean
array1 = np.array([[10, 20, 30], [40, 50, 60]])
print(np.mean(array1))

35.0


In [124]:
#45 finding median
array1 = np.array([[10, 20, 30], [40, 50, 60]])
np.median(array1)

35.0

In [128]:
#46 reversing array
arr = np.arange(10).reshape(-1,10)
arr[:,::-1]

array([[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]])

In [103]:
#47 total non zero elements in array
x = np.array([[0, 10, 20], [0, 30, 40]])
print(np.count_nonzero(x))

4


In [104]:
#48converting 1D array into a 2D array as column
a = np.array((10,20,30))
b = np.array((40,50,60))
c = np.column_stack((a, b))
print(c)

[[10 40]
 [20 50]
 [30 60]]


In [105]:
#49 converting 1D arrays into a 2D array as row
a = np.array((10,20,30))
b = np.array((40,50,60))
c = np.row_stack((a, b))
print(c)

[[10 20 30]
 [40 50 60]]


In [115]:
#50 Replace all odd numbers with -1 
arr1 =np.array(range(10))
print(arr1)
for i in arr1:
    if i%2==1:
        arr1[i] =-1
print("odd numbers replaced by -1")
print(arr1)

[0 1 2 3 4 5 6 7 8 9]
odd numbers replaced by -1
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [133]:
#51 Replace all even numbers with 2
a=np.arange(10)
print(a)

a[a%2==0]=2
print("Even numbers replaced by -1")
print(a)

[0 1 2 3 4 5 6 7 8 9]
Even numbers replaced by -1
[2 1 2 3 2 5 2 7 2 9]


In [117]:
#52 finding unique numbers
no = np.array([1,2,3,4,5,2,4,6,5,7])
np.unique(no)

array([1, 2, 3, 4, 5, 6, 7])

In [122]:
#53 converting integers in float
arr = np.array([1, 2, 3, 4, 5])
arr_float = np.array(arr, dtype='float')
arr_float

array([[ 0., 30., 45., 60., 90.]])

In [130]:
#54 extracting the number ranges from 10 to 20 in an array
b = np.array([10,3,5,2,10,70,43,4,0,14,55,5,8,20,12,11])
print(b[(b >= 5) & (b <= 20)])


[10  5 10 14  5  8 20 12 11]
